# Social Media Links
# The footer include loops over this list to render social icons.
# Set url to "" to hide a platform.

- platform: "Facebook"
  icon: "facebook"
  url: "https://facebook.com/joystrouseauthor"

- platform: "Instagram"
  icon: "instagram"
  url: "https://instagram.com/joystrousewriter"

- platform: "Goodreads"
  icon: "goodreads"
  url: "https://www.goodreads.com/author/show/22090092.Joy_Strouse"

- platform: "Amazon Author Page"
  icon: "amazon"
  url: "https://www.amazon.com/stores/author/B09NTZK99W/about"
